-- 통합계정(SSO) 초기 스키마. 신원(로그인)의 단일 진실.
-- 결제·구독 정보는 여기 두지 않는다(빌링 DB 소관). 여기는 인증 정보만.

CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id   VARCHAR(64)  NOT NULL,   -- 토큰 sub. 타 서비스가 사용자를 가리키는 안정 식별자
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,   -- BCrypt 해시 (평문 저장 금지)
    name          VARCHAR(100),
    status        VARCHAR(20)  NOT NULL DEFAULT 'active',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (external_id),
    UNIQUE (email)
);
