-- 멱등키 영속화. 동일 Idempotency-Key 재요청은 재실행하지 않고 저장된 응답을 반환.
-- 더블클릭·클라이언트 재시도로 인한 이중 구독·이중 청구 방지.
CREATE TABLE idempotency_key (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope         VARCHAR(64)  NOT NULL,       -- 작업 종류(예: subscription:create)
    idem_key      VARCHAR(128) NOT NULL,       -- 클라이언트 제공 키
    customer      VARCHAR(64)  NOT NULL,       -- 요청 고객(external_id) — 키 도용 방지
    status        VARCHAR(20)  NOT NULL,       -- in_progress | completed
    response_body TEXT,                        -- 완료 응답(JSON)
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (scope, idem_key)
);
