-- 문의(contact form) 접수 테이블. 공개 문의 폼 제출을 저장하고 관리자 콘솔에서 열람.
-- 첨부파일은 StorageService(S3/로컬)에 저장하고 키만 보관(원본 bytes는 DB에 넣지 않음).
CREATE TABLE inquiry (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(40)  NOT NULL,               -- 문의 유형(결제·구독 등)
    product_code        VARCHAR(64),                         -- 관련 제품 service_code(선택)
    product_label       VARCHAR(200),                        -- 관련 제품 표시명(플랜·조직 포함, 선택)
    name                VARCHAR(100),                        -- 문의자 이름(선택)
    email               VARCHAR(254) NOT NULL,               -- 회신 이메일(필수)
    message             TEXT         NOT NULL,               -- 문의 내용
    attachment_key      VARCHAR(255),                        -- 스토리지 키(선택)
    attachment_filename VARCHAR(255),                        -- 원본 파일명(선택)
    attachment_size     INTEGER,                             -- 첨부 크기(bytes, 선택)
    status              VARCHAR(20)  NOT NULL DEFAULT 'open', -- open | resolved
    external_id         VARCHAR(64),                         -- 로그인 제출자 SSO external_id(익명이면 NULL)
    client_ip           VARCHAR(64),                         -- 제출 IP(악용 추적·레이트리밋)
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_inquiry_created_at ON inquiry (created_at DESC);
