-- Synub Billing 초기 스키마 (PRD §4.2 기준). 멀티테넌트 대비 company_id 포함.
-- Flyway default-schema = billing 으로 이 스키마에 생성된다.

-- 통합계정 유저 (결제 서비스가 보관하는 최소 정보)
CREATE TABLE customer (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT      NOT NULL,
    external_id VARCHAR(64) NOT NULL,
    email       VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, external_id)
);

-- 제품 카탈로그
CREATE TABLE product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id   BIGINT       NOT NULL,
    service_code VARCHAR(50)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    category     VARCHAR(50),
    description  TEXT,
    domain_url   VARCHAR(255),
    demo_url     VARCHAR(255),
    webhook_url  VARCHAR(255),
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (company_id, service_code)
);

-- 요금제
CREATE TABLE plan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT       NOT NULL REFERENCES product(id),
    plan_code     VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    tagline       VARCHAR(255),
    amount        INTEGER      NOT NULL,
    currency      VARCHAR(3)   NOT NULL DEFAULT 'KRW',
    billing_cycle VARCHAR(10)  NOT NULL,
    features      JSONB,
    is_highlight  BOOLEAN      NOT NULL DEFAULT false,
    status        VARCHAR(20)  NOT NULL DEFAULT 'active',
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (product_id, plan_code)
);

-- 카드 빌링키
CREATE TABLE billing_key (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT       NOT NULL REFERENCES customer(id),
    pg_billing_key VARCHAR(255) NOT NULL,
    card_company   VARCHAR(50),
    card_last4     VARCHAR(4),
    card_type      VARCHAR(20),
    is_primary     BOOLEAN      NOT NULL DEFAULT false,
    status         VARCHAR(20)  NOT NULL DEFAULT 'active',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- 구독
CREATE TABLE subscription (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          BIGINT      NOT NULL REFERENCES customer(id),
    plan_id              BIGINT      NOT NULL REFERENCES plan(id),
    billing_key_id       BIGINT      NOT NULL REFERENCES billing_key(id),
    status               VARCHAR(20) NOT NULL,
    started_at           TIMESTAMPTZ NOT NULL,
    next_billing_date    DATE        NOT NULL,
    canceled_at          TIMESTAMPTZ,
    cancel_at_period_end BOOLEAN     NOT NULL DEFAULT true,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 결제 이력
CREATE TABLE payment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT      NOT NULL REFERENCES subscription(id),
    pg_payment_id   VARCHAR(255),
    amount          INTEGER     NOT NULL,
    status          VARCHAR(20) NOT NULL,
    failure_reason  TEXT,
    receipt_no      VARCHAR(64),
    paid_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_subscription_customer ON subscription(customer_id);
CREATE INDEX idx_subscription_due ON subscription(next_billing_date, status);
CREATE INDEX idx_payment_subscription ON payment(subscription_id);
CREATE INDEX idx_billing_key_customer ON billing_key(customer_id);
