-- M3/M4/M5 — 자동청구·재시도·웹훅 지원 컬럼/테이블.

-- 재시도 횟수 추적 (실패 재시도 정책)
ALTER TABLE subscription ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;

-- 웹훅 발송 감사 로그 (장애 격리·재시도·감사)
CREATE TABLE webhook_delivery (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT      REFERENCES product(id),
    event        VARCHAR(50) NOT NULL,
    url          VARCHAR(255),
    payload      TEXT,
    status       VARCHAR(20) NOT NULL DEFAULT 'pending', -- pending/delivered/failed
    attempts     INTEGER     NOT NULL DEFAULT 0,
    last_error   TEXT,
    response_code INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at TIMESTAMPTZ
);

CREATE INDEX idx_webhook_delivery_event ON webhook_delivery(event);
CREATE INDEX idx_webhook_delivery_status ON webhook_delivery(status);
