-- 조직(구매 회사) + 멤버십·역할. 개인/회사 컨텍스트의 회사 측 기반.
-- (org-owned 구독은 다음 마일스톤 — 이 마이그레이션은 조직·역할 골격만.)

CREATE TABLE organization (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,   -- 신업(운영사) 테넌트
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE membership (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL REFERENCES organization(id),
    customer_id     BIGINT      NOT NULL REFERENCES customer(id),
    role            VARCHAR(20) NOT NULL,   -- owner | billing_manager | member
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (organization_id, customer_id)
);

CREATE INDEX idx_membership_customer ON membership(customer_id);
