-- 조직 멤버 초대. 이메일로 초대(pending) → 초대받은 사람이 로그인(토큰 email) 후 수락 시 멤버십 생성.
-- email 은 소문자로 저장(SSO 계정 이메일과 대소문자 무시 매칭).

CREATE TABLE invitation (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id        BIGINT       NOT NULL REFERENCES organization(id),
    email                  VARCHAR(255) NOT NULL,
    role                   VARCHAR(20)  NOT NULL,   -- member | billing_manager
    status                 VARCHAR(20)  NOT NULL DEFAULT 'pending',  -- pending|accepted|declined|canceled
    invited_by_customer_id BIGINT       REFERENCES customer(id),
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_invitation_email ON invitation(email);
CREATE INDEX idx_invitation_org ON invitation(organization_id);
-- 같은 조직에 같은 이메일의 pending 초대는 하나만
CREATE UNIQUE INDEX uq_invitation_pending ON invitation(organization_id, email) WHERE status = 'pending';
